# Generated by Django 3.0.5 on 2020-04-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_instruments', '0001_initial'),
        ('spectrometry', '0002_gas_gasms_liquid_liquidms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpectrometryCategory',
            new_name='Spectrometry',
        ),
        migrations.AlterUniqueTogether(
            name='liquid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='spectrometry_category',
        ),
        migrations.RemoveField(
            model_name='gasms',
            name='gas_spectrometer',
        ),
        migrations.RemoveField(
            model_name='liquidms',
            name='liquid_spectrometer',
        ),
        migrations.AddField(
            model_name='gasms',
            name='spectrometer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gas_spectrometers', related_query_name='gas_spectrometer', to='spectrometry.Spectrometry'),
        ),
        migrations.AddField(
            model_name='liquidms',
            name='spectrometer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liquid_spectrometers', related_query_name='liquid_spectrometer', to='spectrometry.Spectrometry'),
        ),
        migrations.DeleteModel(
            name='Gas',
        ),
        migrations.DeleteModel(
            name='Liquid',
        ),
    ]
