# Generated by Django 3.0.5 on 2020-04-17 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCChroma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chromatography_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcchromas', related_query_name='lcchroma', to='chromatography.ChromaCategory')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GCChroma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chromatography_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcchromas', related_query_name='gcchroma', to='chromatography.ChromaCategory')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
