# Generated by Django 3.0.5 on 2020-04-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
        ('manufacturers', '0001_initial'),
        ('chromatography', '0002_gcchroma_lcchroma'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('product_code', models.CharField(default='GC-52468', max_length=8, unique=True)),
                ('model', models.CharField(max_length=20, unique=True)),
                ('warranty', models.BooleanField(default=True)),
                ('image', models.URLField()),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.Condition')),
                ('gc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcsystems', related_query_name='gcsystem', to='chromatography.GCChroma')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturer')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
