# Generated by Django 3.0.5 on 2020-04-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0015_auto_20200419_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-5742281', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-8394681', editable=False, max_length=10, unique=True),
        ),
    ]
