# Generated by Django 3.0.5 on 2020-04-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0016_auto_20200419_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-5080307', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-21671', editable=False, max_length=10, unique=True),
        ),
    ]
