# Generated by Django 3.0.5 on 2020-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0020_auto_20200419_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-3855181', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-4781099', editable=False, max_length=10, unique=True),
        ),
    ]
