# Generated by Django 3.0.5 on 2020-04-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0022_auto_20200419_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-5320022', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-699064', editable=False, max_length=10, unique=True),
        ),
    ]
