# Generated by Django 3.0.5 on 2020-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0023_auto_20200419_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-4390841', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-1481881', editable=False, max_length=10, unique=True),
        ),
    ]
