# Generated by Django 3.0.5 on 2020-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_auto_20200416_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
