# Generated by Django 3.0.5 on 2020-04-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0004_auto_20200418_0002'),
        ('process', '0001_initial'),
        ('food_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprocessing',
            name='process_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process'),
        ),
        migrations.AddField(
            model_name='foodprocessing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller'),
        ),
        migrations.AlterUniqueTogether(
            name='foodprocessing',
            unique_together={('name', 'slug')},
        ),
    ]
