# Generated by Django 3.0.5 on 2020-04-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectroscopy', '0002_auto_20200419_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrophotometer',
            name='product_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
