# Generated by Django 3.0.5 on 2020-04-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectroscopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrophotometer',
            name='product_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
