# Generated by Django 3.0.5 on 2020-04-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0010_auto_20200418_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-5446576', editable=False, max_length=10, unique=True),
        ),
    ]
