# Generated by Django 3.0.5 on 2020-04-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0014_auto_20200418_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-2661580', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='product_code',
            field=models.CharField(default='LC-5612886', editable=False, max_length=10, unique=True),
        ),
    ]
