# Generated by Django 3.0.5 on 2020-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200417_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='return_policy',
            field=models.TextField(default='No Return Policy Listed'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shipping_policy',
            field=models.TextField(default='No Shipping Policy Listed'),
        ),
    ]
