# Generated by Django 3.0.5 on 2020-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200416_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='return_policy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='shipping_policy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
