# Generated by Django 3.0.5 on 2020-04-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200417_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='return_policy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shipping_policy',
            field=models.TextField(),
        ),
    ]
