# Generated by Django 3.0.5 on 2020-04-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytical_instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instrumentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromacategories', related_query_name='chromacategory', to='analytical_instruments.Instrumentation')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
