# Generated by Django 3.0.5 on 2020-04-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200416_1054'),
        ('categories', '0002_auto_20200416_0206'),
        ('conditions', '0001_initial'),
        ('manufacturers', '0003_auto_20200416_1054'),
        ('analytical_instruments', '0001_initial'),
        ('chromatography', '0002_gcchroma_lcchroma'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('product_id', models.CharField(max_length=8, unique=True)),
                ('model_number', models.CharField(max_length=20, unique=True)),
                ('warranty', models.BooleanField()),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chromatography_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chromatography.GCChroma')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.Condition')),
                ('instrument_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_instruments.InstrumentCategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.Manufacturer')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller')),
            ],
            options={
                'ordering': ['-updated'],
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
