# Generated by Django 3.0.5 on 2020-04-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0003_gcsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcsystem',
            old_name='model_number',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='gcsystem',
            old_name='seller_name',
            new_name='seller',
        ),
    ]
