# Generated by Django 3.0.5 on 2020-04-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0004_auto_20200416_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcsystem',
            name='gc_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chromatography.GCChroma'),
        ),
        migrations.AlterField(
            model_name='gcsystem',
            name='chromatography_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chromatography.ChromaCategory'),
        ),
    ]
