# Generated by Django 3.0.5 on 2020-04-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
        ('sellers', '0001_initial'),
        ('manufacturers', '0001_initial'),
        ('chromatography', '0004_auto_20200417_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcsystem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='gcsystem',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', related_query_name='condition', to='conditions.Condition'),
        ),
        migrations.AlterField(
            model_name='gcsystem',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', related_query_name='manufacturer', to='manufacturers.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-86707', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='gcsystem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', related_query_name='seller', to='sellers.Seller'),
        ),
    ]
