# Generated by Django 3.0.5 on 2020-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatography', '0005_auto_20200416_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_id',
            field=models.CharField(default='GC-30153', max_length=8, unique=True),
        ),
    ]
