# Generated by Django 3.0.5 on 2020-04-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
        ('manufacturers', '0001_initial'),
        ('sellers', '0004_auto_20200418_0002'),
        ('chromatography', '0011_auto_20200418_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcsystem',
            name='product_code',
            field=models.CharField(default='GC-1473435', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('product_code', models.CharField(default='LC-1738538', editable=False, max_length=10, unique=True)),
                ('model', models.CharField(max_length=255, unique=True)),
                ('warranty', models.BooleanField(default=True)),
                ('image', models.URLField()),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcconditions', related_query_name='lccondition', to='conditions.Condition')),
                ('lc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcs', related_query_name='lc', to='chromatography.LCChroma')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcmanufacturers', related_query_name='lcmanufacturer', to='manufacturers.Manufacturer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcsellers', related_query_name='lcseller', to='sellers.Seller')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
